/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2017-04-24 22:41:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import itemInfo.Item;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("itemInfo.Item");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("        <html>\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("            <title>Your Cart</title>\r\n");
      out.write("            <style>\r\n");
      out.write("                .btn {\r\n");
      out.write("                    background: #aa00ff;\r\n");
      out.write("                    background-image: -webkit-linear-gradient(top, #aa00ff, #242126);\r\n");
      out.write("                    background-image: -moz-linear-gradient(top, #aa00ff, #242126);\r\n");
      out.write("                    background-image: -ms-linear-gradient(top, #aa00ff, #242126);\r\n");
      out.write("                    background-image: -o-linear-gradient(top, #aa00ff, #242126);\r\n");
      out.write("                    background-image: linear-gradient(to bottom, #aa00ff, #242126);\r\n");
      out.write("                    -webkit-border-radius: 28;\r\n");
      out.write("                    -moz-border-radius: 28;\r\n");
      out.write("                    border-radius: 28px;\r\n");
      out.write("                    font-family: Arial;\r\n");
      out.write("                    color: #ffffff;\r\n");
      out.write("                    font-size: 20px;\r\n");
      out.write("                    padding: 10px 20px 10px 20px;\r\n");
      out.write("                    text-decoration: none;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .btn:hover {\r\n");
      out.write("                    background: #4f3c61;\r\n");
      out.write("                    background-image: -webkit-linear-gradient(top, #4f3c61, #791ca8);\r\n");
      out.write("                    background-image: -moz-linear-gradient(top, #4f3c61, #791ca8);\r\n");
      out.write("                    background-image: -ms-linear-gradient(top, #4f3c61, #791ca8);\r\n");
      out.write("                    background-image: -o-linear-gradient(top, #4f3c61, #791ca8);\r\n");
      out.write("                    background-image: linear-gradient(to bottom, #4f3c61, #791ca8);\r\n");
      out.write("                    text-decoration: none;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                body {\r\n");
      out.write("                    background-image: url('images/library-cart.jpg');\r\n");
      out.write("                    background-repeat: no-repeat;\r\n");
      out.write("                    background-attachment: fixed;\r\n");
      out.write("                    font-family: EngraversGothic BT;\r\n");
      out.write("                    font-size: 20px;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                img.b {\r\n");
      out.write("                    border-style: groove;\r\n");
      out.write("                    border-radius: 10px;\r\n");
      out.write("                    border-width: 5px;\r\n");
      out.write("                    margin-left: 3%;\r\n");
      out.write("                    margin-top: 3%;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                h2 {\r\n");
      out.write("                    font-family: Exotc350 Bd BT;\r\n");
      out.write("                    font-size: 17px;\r\n");
      out.write("                    color: blueviolet;\r\n");
      out.write("                    font-style: Bold;\r\n");
      out.write("                    font-size: 40px\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                hr.style14 {\r\n");
      out.write("                    border: 0;\r\n");
      out.write("                    height: 1px;\r\n");
      out.write("                    background-image: -webkit-linear-gradient(left, #f0f0f0, #8c8b8b, #f0f0f0);\r\n");
      out.write("                    background-image: -moz-linear-gradient(left, #f0f0f0, #8c8b8b, #f0f0f0);\r\n");
      out.write("                    background-image: -ms-linear-gradient(left, #f0f0f0, #8c8b8b, #f0f0f0);\r\n");
      out.write("                    background-image: -o-linear-gradient(left, #f0f0f0, #8c8b8b, #f0f0f0);\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                hr.style18 {\r\n");
      out.write("                    height: 30px;\r\n");
      out.write("                    border-style: solid;\r\n");
      out.write("                    border-color: #8c8b8b;\r\n");
      out.write("                    border-width: 1px 0 0 0;\r\n");
      out.write("                    border-radius: 20px;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                hr.style18:before {\r\n");
      out.write("                    display: block;\r\n");
      out.write("                    content: \"\";\r\n");
      out.write("                    height: 30px;\r\n");
      out.write("                    margin-top: -31px;\r\n");
      out.write("                    border-style: solid;\r\n");
      out.write("                    border-color: #8c8b8b;\r\n");
      out.write("                    border-width: 0 0 1px 0;\r\n");
      out.write("                    border-radius: 20px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            </style>\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("            <h2 align=\"center\">Item you are selecting :</h2>\r\n");
      out.write("            <hr class=\"style14\" width=30%/>\r\n");
      out.write("            <form action=\"Transaction\">\r\n");
      out.write("\r\n");
      out.write("                <table align=center cellpadding='30' cellspacing='20'>\r\n");
      out.write("\r\n");
      out.write("                    ");

	String s=(String)session.getAttribute("transac");
	String itemar[]=s.substring(0,s.length()-1).split(",");
	
	for(int i=0;i<itemar.length;i++){
		if(i%4==0)
			out.write(" <tr> ");
		
		out.write(" <td> ");
                    out.write(" <img src="+Item.getImg(Integer.parseInt(itemar[i]))+" width='70' height='100' class='b'/>  <br/> <b>"+Item.getName(Integer.parseInt(itemar[i]))+"</b>");
		out.write(" </td> ");
		
		if(i%4==3)
		out.write(" </tr> ");
		
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("                <br/><br/>\r\n");
      out.write("                <hr class=\"style18\" width=80%/>\r\n");
      out.write("\r\n");
      out.write("                <table width=\"80%\" style=\"margin-right=10%\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td align=\"center\"><input type=\"submit\" value=\"Proceed To Transaction\" class=\"btn\" style=\"margin-left:10%;\"></td>\r\n");
      out.write("                        <td > <input type=\"button\" value=\"ADD Items\" class=\"btn\" style=\"margin-left:70%;\" onclick=\"window.location.href='itemSelect.jsp'\" /></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </form>\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("        </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
