/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2017-04-24 06:35:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class itemSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("        <title>Insert title here</title>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>ItemPage</title>\r\n");
      out.write("        <style type=\"text/CSS\">\r\n");
      out.write("            .design { font-family:EngraversGothic BT; font-size:17px; color:#6EAEA1; font-style: Semi Expanded Bold; } table,td { text-align:center; border-spacing:10; border-width:5px; align:center; border-style: inset; border-color:#FED85D; color: #B56917; } body { background-image: url('images/navy-blue-wallpaper.jpg'); background-repeat: no-repeat; background-attachment: fixed; } img { width: 70px; height: 100px; }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <form action=\"itemSelect\">\r\n");
      out.write("            <div class=\"design\">\r\n");
      out.write("                <b>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"1\"><img src=\"images/catcher-in-the-rye.jpeg\" /></button><br>\"Catcher In The Rye\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"2\"><img src=\"images/diary.jpeg\"               /></button><br>\"The Diary of a Wimpy Kid\"</td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"3\"><img src=\"images/greatexpectations.jpeg\"   /></button><br>\"Great Expectations\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"4\"><img src=\"images/iceage.jpg\"               /></button><br>\"Ice Age: The Meltdown\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"5\"><img src=\"images/janeeyre.jpeg\"            /></button><br>\"Jane Eyre\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"6\"><img src=\"images/junglebook.jpeg\"         /></button><br>\"Jungle Book\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"7\"><img src=\"images/mockingbird.jpeg\"        /></button><br>\"To Kill a Mocking Bird\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"8\"><img src=\"images/one-indian-girl-original.jpeg\" /></button><br>\"One Indian Girl\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"9\"><img src=\"images/Pokemon.jpg\"             /></button><br>\"Pokemon\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"10\"><img src=\"images/prideandprejudice.jpeg\"  /></button><br>\"Pride and Prejudice\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"11\"><img src=\"images/sourcecode.jpeg\"         /></button><br>\"Source Code\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"12\"><img src=\"images/tangled.jpg\"             /></button><br>\"Tangled\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"13\"><img src=\"images/thegreatgatsby.jpeg\"     /></button><br>\"The Great Gatsby\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"14\"><img src=\"images/The-Tenant-of-the-World.jpg\" /></button><br>\"The Tenant of the World\"</td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"15\"><img src=\"images/tintin.jpeg\"             /></button><br>\"Tintin and the Picaros\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"16\"><img  src=\"images/oliver_twist.jpeg\"      /></button><br>\"Oliver Twist\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"17\"><img  src=\"images/mansfield-park.jpeg\"    /></button><br>\"Mansfield Park\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"18\"><img  src=\"images/sense-and-sensibility.jpeg\" /></button><br>\"Sense and Sensibility\"</td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"19\"><img  src=\"images/wuthering.jpeg\" \t\t   /></button><br>\"Wuthering Heights\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"20\"><img  src=\"images/emma.jpeg\" \t\t\t   /></button><br>\"Emma\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"21\"><img  src=\"images/riverpiedra.jpeg\"\t   /></button><br>\"By the River Piedra I Sat Down and Wept\"</td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"22\"><img  src=\"images/alchemist.jpeg\"         /></button><br>\"The Alchemist\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"23\"><img  src=\"images/zahir.jpeg\"             /></button><br>\"The Zahir\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"24\"><img  src=\"images/the_glass_palace.jpeg\"  /></button><br>\"The Glass Palace\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"25\"><img  src=\"images/hunchback.jpg\"          /></button><br>\"The Hunchback of Notro Dame\"</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"26\"><img  src=\"images/nograves.jpeg\"     \t   /></button><br>\"No Graves as Yet\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"27\"><img  src=\"images/lowland.jpeg\"       \t   /></button><br>\"The Lowland\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"28\"><img  src=\"images/namesake.jpg\"       \t   /></button><br>\"The Namesake\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"29\"><img  src=\"images/frankenstein.jpeg\"  \t   /></button><br>\"Frankenstein\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"30\"><img  src=\"images/the_calcutta.jpeg\"      /></button><br>\"The Calcutta Chromosome\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"31\"><img  src=\"images/huckelberryfin.jpeg\"    /></button><br>\"The Adventures of Huckelberry Fin\"</td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"32\"><img  src=\"images/train.jpg\"              /></button><br>\"Train To Pakistan\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"33\"><img  src=\"images/two_little_girls.jpeg\"  /></button><br>\"Two Little Girls in Blue\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"34\"><img  src=\"images/outbreak.jpeg\"          /></button><br>\"Outbreak\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"35\"><img  src=\"images/the_snow_child.jpeg\"    /></button><br>\"The Snow Child\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"36\"><img  src=\"images/midChild.jpeg\" /></button><br>\"Midnight's Children\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"37\"><img  src=\"images/HP1.jpg\" \t\t\t\t /></button><br>\"Harry Potter and The Philosopher's Stone\"</td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"38\"><img  src=\"images/HP2.jpg\" \t\t\t\t /></button><br>\"Harry Potter and The Chamber of Secrets\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"39\"><img  src=\"images/HP3.jpg\" \t\t\t\t /></button><br>\"Harry Potter and the Prisoner of Askaban\"</td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"40\"><img  src=\"images/HP4.jpg\"\t\t\t\t\t /></button><br>\"Harry Potter and the Goblet of Fire\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"41\"><img  src=\"images/HP5.jpg\" \t\t\t\t/></button><br>\"Harry Potter and The Order of The Phoniex \"</td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"42\"><img  src=\"images/HP6.jpeg\" \t\t\t\t/></button><br>\"Harry Potter and the Half Blood Prince\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"43\"><img  src=\"images/HP7.jpg\" \t\t\t\t/></button><br>\"Harry Potter and the Deathly Hallows\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"44\"><img  src=\"images/da_vinci_code.jpeg\" \t\t/></button><br>\"Da Vinci Code\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"45\"><img  src=\"images/angels_and_demons.jpeg\"  /></button><br>\"Angels and Demons\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"46\"><img  src=\"images/digitalfortress.jpeg\" \t/></button><br>\"Digital Fortress\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"47\"><img  src=\"images/inferno.jpeg\" \t\t\t/></button><br>\"Inferno\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"48\"><img  src=\"images/mountains.jpeg\" \t\t    /></button><br>\"And The Mountains Echoed \" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"49\"><img  src=\"images/thekiterunner.jpeg\" \t\t/></button><br>\"The Kite Runner\" </td>\r\n");
      out.write("                        <td><button type=\"submit\" name=\"but\" value=\"50\"><img  src=\"images/thousand.jpeg\" \t\t    /></button><br>\"Thousand Splendid Suns\" </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                </b>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
