/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-08-19 15:48:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class cropInputs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<html>\r\n");
      out.write("\r\n");
      out.write("\t\t<head>\r\n");
      out.write("\t\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\t\t<link href=\"css/floatinglable.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t\t<link href=\"css/form.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t\t<title>Insert title here</title>\r\n");
      out.write("\t\t\t<style>\r\n");
      out.write("\t\t\t\t@media screen and (min-width: 900px) {\r\n");
      out.write("\t\t\t\t\tform {\r\n");
      out.write("\t\t\t\t\t\tmax-width: 80%;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t</style>\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\r\n");
      out.write("\t\t<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
 String ar[]=(String [])request.getAttribute("list");
				String season[]=(String [])request.getAttribute("season");
      out.write("\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"CropInputStore\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"10\" width=\"100%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<legend><span class=\"number\">1</span>Customer basic info</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"name\">Name:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" value=\"");
      out.print(ar[0]);
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"cutomerID\">Customer ID:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print(ar[2]);
      out.write("\" readonly></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"aadhar\">Aadhar ID:</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print(ar[1]);
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<legend><span class=\"number\">2</span>");
      out.print(season[0] );
      out.write(" Season Crops</legend>\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td> <label for=\"crop1\">Crop 1 : </label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print(ar[3]);
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"crop1\"> Crop 2 : </label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print(ar[4]);
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"crop1\">Crop 3 : </label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print(ar[5]);
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"crop1\">Sowing : </label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"sow\" value=\"");
      out.print(season[1]);
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"crop1\">Harvesting : </label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"harv\" value=\"");
      out.print(season[2]);
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<legend><span class=\"number\">3</span>Farm Inputs</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PESTICIDE</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"inputMaterial\" placeholder=\" \" name=\"pesticide\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"floating\">Pesticide Quantity in KG</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"inputMaterial\" placeholder=\" \" id=\"pesticide\" type=\"text\" onfocusout=\"cal(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"floating\">Pesticide price per KG</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"pesticide1\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>FERTILIZER</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"inputMaterial\" placeholder=\" \" name=\"fertilizer\" type=\"text\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"floating\">Fertilizer Quantity in KG</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"inputMaterial\" placeholder=\" \" id=\"fertilizer\" type=\"text\" onfocusout=\"cal(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"floating\">Fertilizer price per KG</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"fertilizer1\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"fert\" style=\"margin: -30px 0 30px 0;\">\r\n");
      out.write("                <option value=\"\">Select Fertilizer Type</option>\r\n");
      out.write("                <option>Nitrogen</option>\r\n");
      out.write("                <option>Phosphorous</option>\r\n");
      out.write("                <option>Potassium</option>\r\n");
      out.write("                </select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>MANURE</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"inputMaterial\" placeholder=\" \" name=\"manure\" type=\"text\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"floating\">Manure Quantity in KG</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"inputMaterial\" placeholder=\" \" id=\"manure\" type=\"text\" onfocusout=\"cal(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"floating\">Manure price per KG</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"manure1\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TOOLS</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"tool\" name=\"tool\">\r\n");
      out.write("                \t\t\t\t\t\t\t<option value=\"0\">Select Tool Type</option>\r\n");
      out.write("                \t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"inputMaterial\" id=\"sub\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[6]);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"floating\">Previous Subscription</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"toolprice\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><button id=\"tot\" type=\"button\">TOTAL</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"total\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=3 align=\"center\"><input type=\"submit\" value=\"Submit Farm Inputs\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script src=\"https://code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t\tvar tool = document.getElementById(\"tool\");\r\n");
      out.write("\t\t\t\t\t\t");

    						ArrayList<String> tool=(ArrayList<String>)request.getAttribute("toolList");
    						for(int i=1;i<=tool.size();i++)
    						{
      out.write("\r\n");
      out.write("\t\t\t\t\t\ttool.options[tool.options.length] = new Option(\"");
      out.print(tool.get(i-1));
      out.write("\", \"");
      out.print(i);
      out.write("\");\r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction cal(e) {\r\n");
      out.write("\t\t\t\t\t\tvar id = $(e).attr('id').toString();\r\n");
      out.write("\t\t\t\t\t\tvar id1 = id + '1';\r\n");
      out.write("\t\t\t\t\t\tvar q1 = parseInt($('#' + id).val());\r\n");
      out.write("\t\t\t\t\t\tvar q2 = parseInt($('input[name='+id+']').val());\r\n");
      out.write("\t\t\t\t\t\t$('#'+id1).val(q1*q2);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$('#tot').click(function () {\r\n");
      out.write("\t\t\t\t\t\tvar pest=0,fert=0,manure=0,tool=0;\r\n");
      out.write("\t\t\t\t\t\tif($('#pesticide1').val()!=\"\" && !isNaN($('#pesticide1').val()))\r\n");
      out.write("\t\t\t\t\t\t\tpest=parseInt($('#pesticide1').val());\r\n");
      out.write("\t\t\t\t\t\tif($('#fertilizer1').val()!=\"\" && !isNaN($('#fertilizer1').val()))\r\n");
      out.write("\t\t\t\t\t\t\tfert=parseInt($('#fertilizer1').val());\r\n");
      out.write("\t\t\t\t\t\tif($('#manure1').val()!=\"\" && !isNaN($('#manure1').val()))\r\n");
      out.write("\t\t\t\t\t\t\tmanure=parseInt($('#manure1').val());\r\n");
      out.write("\t\t\t\t\t\tif($('#tool').val()!=\"\" && !isNaN($('#tool').val()))\r\n");
      out.write("\t\t\t\t\t\t\ttool=parseInt($('#toolprice').val());\r\n");
      out.write("\t\t\t\t\t\tvar tot = pest + fert + manure + tool;\r\n");
      out.write("\t\t\t\t\t\t$('input[name=total').val(tot);\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t</body>\r\n");
      out.write("\r\n");
      out.write("\t\t</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
