/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-08-19 15:49:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class custinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Customer Information</title>\r\n");
      out.write("\t<link href=\"css/form.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t\t<link href=\"css/floatinglable.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t\t<link href=\"css/tabs.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header_menu.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("m", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("0", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<ul id=\"tabs\">\r\n");
      out.write("        <li><a href=\"#\" name=\"tab1\">Personal INFO</a></li>\r\n");
      out.write("        <li><a href=\"#\" name=\"tab2\">CROPS GROWN</a></li>\r\n");
      out.write("        <li><a href=\"#\" name=\"tab3\">FARM INPUTS</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <div id=\"tab1\">\r\n");
      out.write("        ");
String[] ar=(String [])request.getAttribute("pinfo"); 
      out.write("\r\n");
      out.write("        <table align=\"center\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[0] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Customer ID</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[1] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Aadhar ID</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[3] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Phone</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[2] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Name</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[4] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Gender</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("       \r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[5] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Village</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[6] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Block</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[7] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">District</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[8] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">City</label> </div></td>\r\n");
      out.write("\t\t<td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[9] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">State</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(ar[10] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Size</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"tab2\">\r\n");
      out.write("        ");
String[][] crop=(String [][])request.getAttribute("crop"); 
        for(int i=0;i<3;i++){
      out.write("\r\n");
      out.write("        <table align=\"center\" style=\"margin:5px 0 5px 0\">\r\n");
      out.write("        <tr><th colspan=\"2\" align=\"center\"><legend style=\"height:96%;padding:2% 0;\"><span class=\"number\">");
      out.print(i+1 );
      out.write("</span>");
      out.print(crop[i][0] );
      out.write(" SEASON INFO</legend></th></tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(crop[i][1] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">SOWING SEASON</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(crop[i][2] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">HARVESTING SEASON</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(crop[i][3] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">CROP1</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(crop[i][4] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">CROP2</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(crop[i][5] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">CROP3</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    \t");
} 
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("        <div id=\"tab3\">\r\n");
      out.write("        ");
String[] f=(String [])request.getAttribute("finput"); 
      out.write("\r\n");
      out.write("        <table align=\"center\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[0] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Customer ID</label> </div>\r\n");
      out.write("        </td></tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[8] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Subscription</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[9] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Sowing Season</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[10] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Harvesting Season</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[1] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Pesticide Quantity</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[2] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Fertilizer Type</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("         <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[3] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Fertilizer Quantity</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[4] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Manure Quantity</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[5] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Tools Subscribe</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[8] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Tools Subscription Previously</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[6] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Amount DUE</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><div class=\"group\">\r\n");
      out.write("\t\t\t<input class=\"inputMaterial\" placeholder=\" \" type=\"text\" value=\"");
      out.print(f[7] );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t<label class=\"floating\">Total AMOUNT</label> </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            $(\"#content\").find(\"[id^='tab']\").hide(); // Hide all content\r\n");
      out.write("            $(\"#tabs li:first\").attr(\"id\", \"current\"); // Activate the first tab\r\n");
      out.write("            $(\"#content #tab1\").fadeIn(); // Show first tab's content\r\n");
      out.write("\r\n");
      out.write("            $('#tabs a').click(function(e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                if ($(this).closest(\"li\").attr(\"id\") == \"current\") { //detection for current tab\r\n");
      out.write("                    return;\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\"#content\").find(\"[id^='tab']\").hide(); // Hide all content\r\n");
      out.write("                    $(\"#tabs li\").attr(\"id\", \"\"); //Reset id's\r\n");
      out.write("                    $(this).parent().attr(\"id\", \"current\"); // Activate this\r\n");
      out.write("                    $('#' + $(this).attr('name')).fadeIn(); // Show content for the current tab\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
